---
- name: open api port
  ufw:
    rule: allow
    port: '{{ custom_port_prefix }}17'

- name: open rpc port
  ufw:
    rule: allow
    port: '{{ custom_port_prefix }}57'

- name: open grpc port
  ufw:
    rule: allow
    port: '{{ custom_port_prefix }}90'
