# https://docs.ansible.com/ansible/latest/collections/community/general/cloudflare_dns_module.html
---
- name: Create grpc endpoint
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone }}'
    record: '{{ item }}'
    type: A
    value: '{{ ansible_host }}'
    api_token: '{{ cloudflare_token }}'
    proxied: true
  loop:
    - '{{ endpoint_prefix }}-rpc'
    - '{{ endpoint_prefix }}-grpc'
    - '{{ endpoint_prefix }}-api'
