---
- name: Create rpc endpoint
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone }}'
    record: '{{ endpoint_prefix }}-rpc'
    type: A
    value: '{{ ansible_host }}'
    api_token: '{{ cloudflare_token }}'
    proxied: true
  register: record

- name: Create grpc endpoint
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone }}'
    record: '{{ endpoint_prefix }}-grpc'
    type: A
    value: '{{ ansible_host }}'
    api_token: '{{ cloudflare_token }}'
    proxied: true
  register: record

- name: Create api endpoint
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_zone }}'
    record: '{{ endpoint_prefix }}-api'
    type: A
    value: '{{ ansible_host }}'
    api_token: '{{ cloudflare_token }}'
    proxied: true
  register: record
