---
- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  roles:
    - setup
    - node_install
    - node_initialize
    - node_configure
    - support_public_endpoints
    - node_launch
    - support_seed
