---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - prepare

- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - node_install
    - node_initialize
    - node_configure
    - node_launch
