---
- name: install unzip
  apt:
    name: unzip
    state: present

- name: download binary
  get_url:
    url: '{{ binary }}'
    dest: '/tmp/binary.zip'
    mode: '0700'
    force: yes

- name: unarchive binary
  unarchive:
    src: '/tmp/binary.zip'
    remote_src: yes
    dest: '/tmp'
    mode: '0644'

- name: Copy binary
  copy:
    remote_src: true
    src: '/tmp/{{ daemon }}'
    dest: '{{ user_dir }}/go/bin/{{ daemon }}'
    mode: '0755'
