---
- name: Update minimum gas price on config file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: '^minimum-gas-prices ='
    line: 'minimum-gas-prices = "{{ minimum_gas_price }}"'
    state: present
  when: minimum_gas_price is defined

- name: Update Polkachu internal database
  uri:
    url: https://polkachu.com/api/v2/chain_minimum_gas_price_update
    method: POST
    body_format: json
    body:
      network: '{{ network }}'
      type: '{{ network_type }}'
      minimum_gas_price: '{{ minimum_gas_price }}'
      secret: '{{ polkachu_website_secret }}'
  when: polkachu_website_secret is defined and (type == 'main' or type == 'test')

- name: Restart cosmovisor service
  become: true
  systemd:
    name: '{{ network }}'
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Ensure it is running
  uri:
    url: 'http://localhost:{{ custom_port_prefix }}61'
    method: GET
    status_code: 200
  ignore_errors: true
