---
- meta: end_play
  when: (prepare is defined) and (prepare|bool is false)

- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: install node_exporter
  import_tasks: node_exporter.yml
  when: node_exporter|bool == true

- name: install promtail
  import_tasks: promtail.yml
  when: promtail|bool == true

- name: firewall setup
  import_tasks: firewall.yml

- name: install nginx
  import_tasks: nginx.yml

- name: install cosmos software
  import_tasks: cosmos_software.yml
  when: cosmos_software|default(true)|bool == true
