# https://docs.ansible.com/ansible/latest/collections/community/docker/
---
# Install Docker
# --
- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: add user permissions
  shell: "usermod -aG docker {{ ansible_user }}"

- name: ensure docker is started
  service:
    name: docker
    state: started
    enabled: yes

handlers:
  - name: restart docker
    service: 
      name: docker 
      state: restarted

# Installs Docker Python SDK
# --
- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: "{{ ansible_user }}"
  pip:
    name:
      - docker
      - docker-compose
