---
- name: setup tenderduty
  when: type != 'relayer'
  block: 
    - name: set host ip
      set_fact:
        host_ip: '{{ ansible_host }}'
    - name: change host to tenderseed
      set_fact:
        ansible_host: '{{ tenderduty_host }}'

    - name: set network endpoint prefix
      set_fact: 
        endpoint_prefix: '{{ "testnet-" if type == "testnet" else "" }}{{ custom_network | default(network) }}'

    # ensure docker is installed
    - name: do initial configuration
      run_once: true
      block: 
        - name: install docker
          include_tasks: install_docker.yml

    