network: alignedlayer
folder: '.alignedlayer'
daemon: alignedlayerd
chain_id: alignedlayer
node_version: v0.1.0
repo: 'https://github.com/yetanotherco/aligned_layer_tendermint.git'
binary: 'https://github.com/yetanotherco/aligned_layer_tendermint/releases/download/v0.1.0/alignedlayerd'
binary_processing: default
genesis: 'https://snapshots.polkachu.com/testnet-genesis/alignedlayer/genesis.json'
peers: '4aadf13668b6fcb33f0e5b4a6e5bc267712c7dac@64.226.93.215:26656,c52d1a11c97dfd609693b35ce63834bee140d5ef@185.254.97.211:26656,8abda16310e84ee8ed2388807614a101ce38dd20@143.110.172.11:26656,c355b86c882d05a83f84afba379291d7b954b28f@65.108.236.43:21256'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:27556'
custom_port_prefix: 275
minimum_gas_price: 0.001stake

# [Optional] Snapshot
snapshot_hour: 0
snapshot_minute: 0
