# testnet2
network: injective
folder: '.injectived'
daemon: injectived
chain_id: injective-888
genesis: https://snapshots.polkachu.com/testnet-genesis/injective/genesis.json
app_file: https://raw.githubusercontent.com/InjectiveLabs/testnet/master/corfu/70001/app.toml
config_file: https://raw.githubusercontent.com/InjectiveLabs/testnet/master/corfu/70001/config.toml
repo: https://github.com/InjectiveFoundation/injective-core
node_version: v1.16.4
minimum_gas_price: '500000000inj'
custom_port_prefix: 143
upgrade_folder: v1.16.4
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 4
snapshot_minute: 0
wasm: 'outside'
