---
- name: Make sure the folder does not exist
  file:
    state: absent
    path: '{{ user_dir }}/horcrux'
    
- name: install apt packages
  become: true
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - make
    - build-essential
    - gcc
    - git

- name: Download go
  get_url:
    url: 'https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz'
    dest: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: unarchive go
  become: true
  unarchive:
    src: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/usr/local/'
    owner: root
    group: root
    mode: '0755'

- name: Change go folder permission
  file:
    path: '{{ user_dir }}/go'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: true
    mode: '0755'

- name: copy .profile
  template:
    src: 'profile.j2'
    dest: '{{ user_dir }}/.profile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0600'

- name: Clone horcrux repo
  git:
    repo: '{{ horcrux_repo }}'
    dest: '{{ user_dir }}/horcrux'

- name: Install horcrux
  command: '{{ item }}'
  args:
    chdir: '{{ user_dir }}/horcrux'
  with_items:
    - 'git fetch'
    - 'git checkout {{ horcrux_version }}'
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'

- name: Copy horcrux service file
  become: true
  template:
    src: 'horcrux.service.j2'
    dest: '/etc/systemd/system/horcrux.service'
    owner: root
    group: root
    mode: 600

- name: stop horcrux service
  become: true
  systemd:
    name: horcrux
    state: stopped
    daemon_reload: true
    enabled: true
  changed_when: false
